module.exports = {
  darkMode: 'class',
  content: [
    "./**/*.razor",
    "./**/*.cshtml",
    "./**/*.html",
    "./wwwroot/js/**/*.js",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#f0eded",
        "on-error-container": "#93000a",
        "primary-fixed": "#c4efa3",
        "outline": "#73796c",
        "on-primary-fixed-variant": "#2c4f15",
        "on-background": "#1c1b1b",
        "tertiary-fixed": "#ffdf9c",
        "outline-variant": "#c3c9b9",
        "tertiary-container": "#5c4401",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "canopy-sky": "#5B8BA0",
        "on-primary": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-tint": "#43682b",
        "surface-dim": "#dcd9d9",
        "on-error": "#ffffff",
        "on-primary-container": "#98c27b",
        "surface-container-lowest": "#ffffff",
        "stone": "#6B6B6B",
        "secondary-fixed": "#ffdfa0",
        "on-tertiary-fixed": "#251a00",
        "on-surface": "#1c1b1b",
        "harvest": "#D4A017",
        "primary-container": "#2d5016",
        "on-secondary-fixed": "#261a00",
        "primary": "#173901",
        "inverse-on-surface": "#f3f0ef",
        "on-surface-variant": "#43493d",
        "forest": "#4A7C59",
        "on-primary-fixed": "#0a2100",
        "surface-container-highest": "#e5e2e1",
        "on-secondary-container": "#785800",
        "inverse-surface": "#313030",
        "bark-red": "#8B2635",
        "surface": "#FFFFFF",
        "secondary-fixed-dim": "#ecc165",
        "on-tertiary-container": "#d4b268",
        "secondary": "#795900",
        "background": "#F5F0EB",
        "on-tertiary-fixed-variant": "#5b4300",
        "primary-fixed-dim": "#a8d38a",
        "tertiary-fixed-dim": "#e5c276",
        "tertiary": "#402f00",
        "surface-variant": "#e5e2e1",
        "error": "#ba1a1a",
        "surface-container-high": "#eae7e7",
        "secondary-container": "#fed174",
        "inverse-primary": "#a8d38a",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#5c4300",
        "surface-bright": "#fcf9f8"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "topbar-height": "64px",
        "sidebar-expanded": "280px",
        "base": "4px",
        "sidebar-collapsed": "72px",
        "container-padding": "24px",
        "drawer-width": "720px",
        "gutter": "16px",
      },
      fontFamily: {
        "data-mono": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "label-caps": ["Inter"],
        "headline-xl": ["Geist"],
        "body-md": ["Inter"],
        "headline-md": ["Geist"],
        "headline-lg": ["Geist"],
      },
      fontSize: {
        "data-mono": ["13px", { lineHeight: "18px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
