// <auto-generated />
using System;
using Arzly.Api.Infrastructure.Data.DataBaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arzly.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427175637_Initial_migration")]
    partial class Initial_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Arzly.Api.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("ItemsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1b1a2c8-4e5f-4f6a-8b7c-9d0e1f2a3b4c"),
                            Description = "Gadgets and devices",
                            ImageUrl = "https://example.com/electronics.jpg",
                            ItemsCount = 0,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("e2b2a2c9-5d4e-4f3a-9b8c-7d6e5f4a3b2c"),
                            Description = "Cars, bikes and more",
                            ImageUrl = "https://example.com/vehicles.jpg",
                            ItemsCount = 0,
                            Name = "Vehicles"
                        },
                        new
                        {
                            Id = new Guid("e3b3a2ca-6f5e-4f2a-8b7c-9d0e1f2a3b4c"),
                            Description = "Houses and apartments",
                            ImageUrl = "https://example.com/realestate.jpg",
                            ItemsCount = 0,
                            Name = "Real Estate"
                        });
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ContextRole")
                        .HasColumnType("int");

                    b.Property<string>("InitiatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDiscontinued")
                        .HasColumnType("bit");

                    b.Property<Guid?>("JobListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("InitiatorId");

                    b.HasIndex("JobListingId");

                    b.HasIndex("ListingId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("51b1a2c3-4e5f-4f6a-8b7c-9d0e1f2a3b4c"),
                            ContextRole = 0,
                            InitiatorId = "8f3b2a1c-5d4e-4f3a-9b8c-7d6e5f4a3b2c",
                            IsArchived = false,
                            IsDeleted = false,
                            IsDiscontinued = false,
                            LastActivity = new DateTime(2026, 4, 27, 17, 56, 36, 508, DateTimeKind.Utc).AddTicks(8871),
                            ListingId = new Guid("11b1a2c3-4e5f-4f6a-8b7c-9d0e1f2a3b4c"),
                            ReceiverId = "7c9e6679-7425-40de-944b-e07fc1f90ae7"
                        });
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.HasIndex("SentAt");

                    b.ToTable("ChatMessages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("61b1a2c3-4e5f-4f6a-8b7c-9d0e1f2a3b4c"),
                            ChatId = new Guid("51b1a2c3-4e5f-4f6a-8b7c-9d0e1f2a3b4c"),
                            IsRead = true,
                            ReadAt = new DateTime(2026, 4, 27, 17, 51, 36, 509, DateTimeKind.Utc).AddTicks(3416),
                            ReceiverId = "7c9e6679-7425-40de-944b-e07fc1f90ae7",
                            SenderId = "8f3b2a1c-5d4e-4f3a-9b8c-7d6e5f4a3b2c",
                            SentAt = new DateTime(2026, 4, 27, 17, 46, 36, 509, DateTimeKind.Utc).AddTicks(2942),
                            Text = "Hi, is the iPhone still available?"
                        },
                        new
                        {
                            Id = new Guid("62b2a2c4-5d4e-4f3a-9b8c-7d6e5f4a3b2c"),
                            ChatId = new Guid("51b1a2c3-4e5f-4f6a-8b7c-9d0e1f2a3b4c"),
                            IsRead = false,
                            ReceiverId = "8f3b2a1c-5d4e-4f3a-9b8c-7d6e5f4a3b2c",
                            SenderId = "7c9e6679-7425-40de-944b-e07fc1f90ae7",
                            SentAt = new DateTime(2026, 4, 27, 17, 54, 36, 509, DateTimeKind.Utc).AddTicks(3753),
                            Text = "Yes, it is!"
                        });
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.JobListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ContactMethod")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EducationLevel")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPromoted")
                        .HasColumnType("bit");

                    b.Property<int>("JobField")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Languages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("PromotionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PromotionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PromotionType")
                        .HasColumnType("int");

                    b.Property<double?>("SalaryMax")
                        .HasColumnType("float");

                    b.Property<double?>("SalaryMin")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("WorkplaceType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LocationId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Status");

                    b.ToTable("JobListings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("21b1a2c3-4e5f-4f6a-8b7c-9d0e1f2a3b4c"),
                            CreatedAt = new DateTime(2026, 4, 27, 17, 56, 36, 508, DateTimeKind.Utc).AddTicks(5415),
                            Description = "Join our team to build amazing ASP.NET Core apps",
                            EducationLevel = 3,
                            Email = "hr@techcorp.com",
                            EmploymentType = 0,
                            ExperienceLevel = 0,
                            IsPromoted = false,
                            JobField = 22,
                            LocationId = new Guid("92b2a2c4-5d4e-4f3a-9b8c-7d6e5f4a3b2c"),
                            Name = "Tech Corp",
                            OwnerId = "8f3b2a1c-5d4e-4f3a-9b8c-7d6e5f4a3b2c",
                            PhoneNumber = "5551234",
                            SalaryMax = 120000.0,
                            SalaryMin = 80000.0,
                            Status = 1,
                            Title = "Senior C# Developer",
                            Type = 1
                        });
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ContactMethod")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.PrimitiveCollection<string>("ImagesUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPriceNegotiable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPromoted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("PickupLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("PrimaryImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime?>("PromotionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PromotionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PromotionType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("SubcategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PickupLocationId");

                    b.HasIndex("Status");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("Listings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11b1a2c3-4e5f-4f6a-8b7c-9d0e1f2a3b4c"),
                            CategoryId = new Guid("e1b1a2c8-4e5f-4f6a-8b7c-9d0e1f2a3b4c"),
                            ContactMethod = 0,
                            CreatedAt = new DateTime(2026, 4, 27, 17, 56, 36, 507, DateTimeKind.Utc).AddTicks(5309),
                            Description = "Excellent condition, 256GB",
                            ImagesUrl = "[]",
                            IsPriceNegotiable = false,
                            IsPromoted = false,
                            Name = "John Doe",
                            OwnerId = "7c9e6679-7425-40de-944b-e07fc1f90ae7",
                            PhoneNumber = "1234567890",
                            PickupLocationId = new Guid("91b1a2c3-4e5f-4f6a-8b7c-9d0e1f2a3b4c"),
                            Price = 999.99000000000001,
                            Status = 1,
                            SubcategoryId = new Guid("81b1a2c3-4e5f-4f6a-8b7c-9d0e1f2a3b4c"),
                            Title = "iPhone 15 Pro"
                        },
                        new
                        {
                            Id = new Guid("12b2a2c4-5d4e-4f3a-9b8c-7d6e5f4a3b2c"),
                            CategoryId = new Guid("e2b2a2c9-5d4e-4f3a-9b8c-7d6e5f4a3b2c"),
                            ContactMethod = 1,
                            CreatedAt = new DateTime(2026, 4, 27, 17, 56, 36, 507, DateTimeKind.Utc).AddTicks(8213),
                            Description = "Barely used, full self-driving",
                            ImagesUrl = "[]",
                            IsPriceNegotiable = false,
                            IsPromoted = false,
                            Name = "Jane Smith",
                            OwnerId = "8f3b2a1c-5d4e-4f3a-9b8c-7d6e5f4a3b2c",
                            PhoneNumber = "0987654321",
                            PickupLocationId = new Guid("92b2a2c4-5d4e-4f3a-9b8c-7d6e5f4a3b2c"),
                            Price = 35000.0,
                            Status = 1,
                            SubcategoryId = new Guid("82b2a2c4-5d4e-4f3a-9b8c-7d6e5f4a3b2c"),
                            Title = "Tesla Model 3"
                        },
                        new
                        {
                            Id = new Guid("13b3a2c5-6f5e-4f2a-8b7c-9d0e1f2a3b4c"),
                            CategoryId = new Guid("e3b3a2ca-6f5e-4f2a-8b7c-9d0e1f2a3b4c"),
                            ContactMethod = 0,
                            CreatedAt = new DateTime(2026, 4, 27, 17, 56, 36, 507, DateTimeKind.Utc).AddTicks(8224),
                            Description = "2 bedrooms, city view",
                            ImagesUrl = "[]",
                            IsPriceNegotiable = false,
                            IsPromoted = false,
                            Name = "John Doe",
                            OwnerId = "7c9e6679-7425-40de-944b-e07fc1f90ae7",
                            PhoneNumber = "1234567890",
                            PickupLocationId = new Guid("91b1a2c3-4e5f-4f6a-8b7c-9d0e1f2a3b4c"),
                            Price = 2500.0,
                            Status = 1,
                            SubcategoryId = new Guid("83b3a2c5-6f5e-4f2a-8b7c-9d0e1f2a3b4c"),
                            Title = "Modern Apartment"
                        });
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.PickupLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("Label")
                        .HasColumnType("int");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lon")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PickupLocations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("91b1a2c3-4e5f-4f6a-8b7c-9d0e1f2a3b4c"),
                            Address = "123 Main St, New York",
                            IsDefault = true,
                            Label = 0,
                            Lat = 40.712800000000001,
                            Lon = -74.006,
                            UserId = "7c9e6679-7425-40de-944b-e07fc1f90ae7"
                        },
                        new
                        {
                            Id = new Guid("92b2a2c4-5d4e-4f3a-9b8c-7d6e5f4a3b2c"),
                            Address = "456 Side St, Los Angeles",
                            IsDefault = true,
                            Label = 1,
                            Lat = 34.052199999999999,
                            Lon = -118.2437,
                            UserId = "8f3b2a1c-5d4e-4f3a-9b8c-7d6e5f4a3b2c"
                        });
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.SavedListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("UserId", "ListingId")
                        .IsUnique();

                    b.ToTable("SavedListings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("31b1a2c3-4e5f-4f6a-8b7c-9d0e1f2a3b4c"),
                            ListingId = new Guid("11b1a2c3-4e5f-4f6a-8b7c-9d0e1f2a3b4c"),
                            SavedAt = new DateTime(2026, 4, 27, 17, 56, 36, 509, DateTimeKind.Utc).AddTicks(6100),
                            UserId = "8f3b2a1c-5d4e-4f3a-9b8c-7d6e5f4a3b2c"
                        });
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.SearchQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("SearchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SearchQueries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("41b1a2c3-4e5f-4f6a-8b7c-9d0e1f2a3b4c"),
                            Query = "iPhone 15",
                            SearchedAt = new DateTime(2026, 4, 27, 17, 56, 36, 509, DateTimeKind.Utc).AddTicks(8516),
                            UserId = "8f3b2a1c-5d4e-4f3a-9b8c-7d6e5f4a3b2c"
                        });
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.SubCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ItemsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("81b1a2c3-4e5f-4f6a-8b7c-9d0e1f2a3b4c"),
                            CategoryId = new Guid("e1b1a2c8-4e5f-4f6a-8b7c-9d0e1f2a3b4c"),
                            Description = "Smartphones and accessories",
                            ItemsCount = 0,
                            Name = "Mobile Phones"
                        },
                        new
                        {
                            Id = new Guid("82b2a2c4-5d4e-4f3a-9b8c-7d6e5f4a3b2c"),
                            CategoryId = new Guid("e2b2a2c9-5d4e-4f3a-9b8c-7d6e5f4a3b2c"),
                            Description = "Sedans, SUVs and more",
                            ItemsCount = 0,
                            Name = "Cars"
                        },
                        new
                        {
                            Id = new Guid("83b3a2c5-6f5e-4f2a-8b7c-9d0e1f2a3b4c"),
                            CategoryId = new Guid("e3b3a2ca-6f5e-4f2a-8b7c-9d0e1f2a3b4c"),
                            Description = "Rent or buy apartments",
                            ItemsCount = 0,
                            Name = "Apartments"
                        });
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedToId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("ListingId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("81b1a2c3-4e5f-4f6a-8b7c-9d0e1f2a3b4c"),
                            CreatedAt = new DateTime(2026, 4, 27, 17, 56, 36, 510, DateTimeKind.Utc).AddTicks(1700),
                            Priority = 2,
                            Status = 0,
                            Subject = "Technical Issue",
                            UserId = "7c9e6679-7425-40de-944b-e07fc1f90ae7"
                        });
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.TicketAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketAttachments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b1a2c3-4e5f-4f6a-8b7c-9d0e1f2a3b4c"),
                            ContentType = "image/jpeg",
                            FileName = "screenshot.jpg",
                            FileSize = 1024L,
                            FileUrl = "https://example.com/screenshot.jpg",
                            TicketId = new Guid("81b1a2c3-4e5f-4f6a-8b7c-9d0e1f2a3b4c"),
                            UploadedAt = new DateTime(2026, 4, 27, 17, 56, 36, 510, DateTimeKind.Utc).AddTicks(5334)
                        });
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.TicketMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsInternalNote")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketMessages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("91b1a2c3-4e5f-4f6a-8b7c-9d0e1f2a3b4c"),
                            IsInternalNote = false,
                            Message = "I am having trouble with the app",
                            ReceiverId = "8f3b2a1c-5d4e-4f3a-9b8c-7d6e5f4a3b2c",
                            SenderId = "7c9e6679-7425-40de-944b-e07fc1f90ae7",
                            SentAt = new DateTime(2026, 4, 27, 17, 56, 36, 510, DateTimeKind.Utc).AddTicks(8868),
                            TicketId = new Guid("81b1a2c3-4e5f-4f6a-8b7c-9d0e1f2a3b4c")
                        });
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.UserActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("TargetId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TargetType")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("Timestamp");

                    b.ToTable("UserActivityLogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1b1a2c3-4e5f-4f6a-8b7c-9d0e1f2a3b4c"),
                            ActionType = 0,
                            ActorId = "7c9e6679-7425-40de-944b-e07fc1f90ae7",
                            ActorRole = "User",
                            IsSuccess = true,
                            TargetType = 0,
                            Timestamp = new DateTime(2026, 4, 27, 17, 56, 36, 511, DateTimeKind.Utc).AddTicks(2024)
                        });
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.UserPreference", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("EmailNotifications")
                        .HasColumnType("bit");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<bool>("PushNotifications")
                        .HasColumnType("bit");

                    b.Property<int>("Theme")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences");

                    b.HasData(
                        new
                        {
                            UserId = "7c9e6679-7425-40de-944b-e07fc1f90ae7",
                            EmailNotifications = true,
                            Language = 0,
                            PushNotifications = true,
                            Theme = 2,
                            UpdatedAt = new DateTime(2026, 4, 27, 17, 56, 36, 511, DateTimeKind.Utc).AddTicks(4957)
                        },
                        new
                        {
                            UserId = "8f3b2a1c-5d4e-4f3a-9b8c-7d6e5f4a3b2c",
                            EmailNotifications = false,
                            Language = 1,
                            PushNotifications = false,
                            Theme = 1,
                            UpdatedAt = new DateTime(2026, 4, 27, 17, 56, 36, 511, DateTimeKind.Utc).AddTicks(5194)
                        });
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.UserReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<string>("ReportedUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReporterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolvedById")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("ReportedUserId");

                    b.HasIndex("ReporterId");

                    b.ToTable("UserReports");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1b1a2c3-4e5f-4f6a-8b7c-9d0e1f2a3b4c"),
                            CreatedAt = new DateTime(2026, 4, 27, 17, 56, 36, 511, DateTimeKind.Utc).AddTicks(7843),
                            IsResolved = false,
                            Notes = "User is spamming messages",
                            Reason = 0,
                            ReportedUserId = "8f3b2a1c-5d4e-4f3a-9b8c-7d6e5f4a3b2c",
                            ReporterId = "7c9e6679-7425-40de-944b-e07fc1f90ae7"
                        });
                });

            modelBuilder.Entity("Arzly.Api.Domain.ListingOwned.BabyChildDetails", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AgeRange")
                        .HasColumnType("int");

                    b.Property<int?>("Condition")
                        .HasColumnType("int");

                    b.Property<int?>("CribFurnitureType")
                        .HasColumnType("int");

                    b.Property<int?>("FeedingType")
                        .HasColumnType("int");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("StrollerSeatType")
                        .HasColumnType("int");

                    b.HasKey("ListingId");

                    b.ToTable("BabyChildDetails");
                });

            modelBuilder.Entity("Arzly.Api.Domain.ListingOwned.ElectronicsDetails", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AudioBrand")
                        .HasColumnType("int");

                    b.Property<int?>("CameraBrand")
                        .HasColumnType("int");

                    b.Property<int?>("CameraType")
                        .HasColumnType("int");

                    b.Property<int?>("CleaningApplianceType")
                        .HasColumnType("int");

                    b.Property<int?>("CompatibleConsole")
                        .HasColumnType("int");

                    b.Property<int?>("ComputerAccessoryType")
                        .HasColumnType("int");

                    b.Property<int?>("ComputerBrand")
                        .HasColumnType("int");

                    b.Property<int?>("ComputerColor")
                        .HasColumnType("int");

                    b.Property<int?>("ComputerScreenSize")
                        .HasColumnType("int");

                    b.Property<int?>("ComputerStorage")
                        .HasColumnType("int");

                    b.Property<int?>("ComputerType")
                        .HasColumnType("int");

                    b.Property<int?>("Condition")
                        .HasColumnType("int");

                    b.Property<int?>("CoolingHeatingType")
                        .HasColumnType("int");

                    b.Property<int?>("DisplayTechnology")
                        .HasColumnType("int");

                    b.Property<int?>("GameCondition")
                        .HasColumnType("int");

                    b.Property<int?>("GameGenre")
                        .HasColumnType("int");

                    b.Property<int?>("GamingBrand")
                        .HasColumnType("int");

                    b.Property<int?>("GamingType")
                        .HasColumnType("int");

                    b.Property<int?>("KitchenApplianceType")
                        .HasColumnType("int");

                    b.Property<int?>("Processor")
                        .HasColumnType("int");

                    b.Property<int?>("RamSize")
                        .HasColumnType("int");

                    b.Property<int?>("ScreenSize")
                        .HasColumnType("int");

                    b.Property<int?>("StorageType")
                        .HasColumnType("int");

                    b.Property<int?>("TVBrand")
                        .HasColumnType("int");

                    b.Property<int?>("TVType")
                        .HasColumnType("int");

                    b.Property<int?>("WashingMachineBrand")
                        .HasColumnType("int");

                    b.HasKey("ListingId");

                    b.ToTable("ElectronicsDetails");
                });

            modelBuilder.Entity("Arzly.Api.Domain.ListingOwned.FashionDetails", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Condition")
                        .HasColumnType("int");

                    b.Property<int?>("CosmeticType")
                        .HasColumnType("int");

                    b.Property<int?>("JewelryMaterial")
                        .HasColumnType("int");

                    b.Property<int?>("JewelryType")
                        .HasColumnType("int");

                    b.Property<int?>("MensAccessoryType")
                        .HasColumnType("int");

                    b.Property<int?>("MensClothingType")
                        .HasColumnType("int");

                    b.Property<int?>("WatchGender")
                        .HasColumnType("int");

                    b.Property<int?>("WomensAccessoryType")
                        .HasColumnType("int");

                    b.Property<int?>("WomensClothingType")
                        .HasColumnType("int");

                    b.HasKey("ListingId");

                    b.ToTable("FashionDetails");
                });

            modelBuilder.Entity("Arzly.Api.Domain.ListingOwned.FurnitureDetails", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BathroomType")
                        .HasColumnType("int");

                    b.Property<int?>("BedroomType")
                        .HasColumnType("int");

                    b.Property<int?>("Condition")
                        .HasColumnType("int");

                    b.Property<int?>("DiningRoomType")
                        .HasColumnType("int");

                    b.Property<int?>("GardenType")
                        .HasColumnType("int");

                    b.Property<int?>("HomeDecorType")
                        .HasColumnType("int");

                    b.Property<int?>("KitchenwareType")
                        .HasColumnType("int");

                    b.Property<int?>("LivingRoomType")
                        .HasColumnType("int");

                    b.HasKey("ListingId");

                    b.ToTable("FurnitureDetails");
                });

            modelBuilder.Entity("Arzly.Api.Domain.ListingOwned.HobbiesDetails", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BookLanguage")
                        .HasColumnType("int");

                    b.Property<int?>("BookType")
                        .HasColumnType("int");

                    b.Property<int?>("CollectibleType")
                        .HasColumnType("int");

                    b.Property<int?>("Condition")
                        .HasColumnType("int");

                    b.Property<int?>("HobbyGameType")
                        .HasColumnType("int");

                    b.Property<int?>("InstrumentType")
                        .HasColumnType("int");

                    b.Property<int?>("MovieGenre")
                        .HasColumnType("int");

                    b.HasKey("ListingId");

                    b.ToTable("HobbiesDetails");
                });

            modelBuilder.Entity("Arzly.Api.Domain.ListingOwned.PetsDetails", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnimalType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BirdAgeGroup")
                        .HasColumnType("int");

                    b.Property<int?>("BirdSpecies")
                        .HasColumnType("int");

                    b.Property<int?>("CatAgeRange")
                        .HasColumnType("int");

                    b.Property<int?>("CatBreed")
                        .HasColumnType("int");

                    b.Property<int?>("DogAgeRange")
                        .HasColumnType("int");

                    b.Property<int?>("DogBreed")
                        .HasColumnType("int");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("GroomingType")
                        .HasColumnType("int");

                    b.Property<bool?>("IsVaccinated")
                        .HasColumnType("bit");

                    b.Property<int?>("PetAccessoryType")
                        .HasColumnType("int");

                    b.Property<int?>("PetFoodType")
                        .HasColumnType("int");

                    b.Property<int?>("PetServiceType")
                        .HasColumnType("int");

                    b.Property<int?>("PetToyType")
                        .HasColumnType("int");

                    b.HasKey("ListingId");

                    b.ToTable("PetsDetails");
                });

            modelBuilder.Entity("Arzly.Api.Domain.ListingOwned.PhonesDetails", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AccessoryBrand")
                        .HasColumnType("int");

                    b.Property<int?>("AccessoryItemType")
                        .HasColumnType("int");

                    b.Property<int?>("BandColor")
                        .HasColumnType("int");

                    b.Property<int?>("BandMaterial")
                        .HasColumnType("int");

                    b.Property<int?>("Color")
                        .HasColumnType("int");

                    b.Property<int?>("MembershipType")
                        .HasColumnType("int");

                    b.Property<int?>("Operator")
                        .HasColumnType("int");

                    b.Property<int?>("PhoneBrand")
                        .HasColumnType("int");

                    b.Property<int?>("PhoneCondition")
                        .HasColumnType("int");

                    b.Property<int?>("Storage")
                        .HasColumnType("int");

                    b.Property<int?>("WatchBrand")
                        .HasColumnType("int");

                    b.Property<int?>("WatchStorage")
                        .HasColumnType("int");

                    b.HasKey("ListingId");

                    b.ToTable("PhonesDetails");
                });

            modelBuilder.Entity("Arzly.Api.Domain.ListingOwned.RealEstateDetails", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int?>("Bedrooms")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("ChaletFeatures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChaletType")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("CommercialFeatures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CommercialType")
                        .HasColumnType("int");

                    b.Property<int?>("Condition")
                        .HasColumnType("int");

                    b.Property<bool?>("Equipped")
                        .HasColumnType("bit");

                    b.PrimitiveCollection<string>("Features")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Floor")
                        .HasColumnType("int");

                    b.Property<int?>("Furnished")
                        .HasColumnType("int");

                    b.Property<int?>("LandType")
                        .HasColumnType("int");

                    b.Property<int?>("ListingType")
                        .HasColumnType("int");

                    b.Property<int?>("Ownership")
                        .HasColumnType("int");

                    b.Property<int?>("PropertyAge")
                        .HasColumnType("int");

                    b.Property<int?>("PropertyType")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("RoomFeatures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RoomFurnished")
                        .HasColumnType("bit");

                    b.Property<double?>("Size")
                        .HasColumnType("float");

                    b.HasKey("ListingId");

                    b.ToTable("RealEstateDetails");
                });

            modelBuilder.Entity("Arzly.Api.Domain.ListingOwned.ServicesDetails", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("EventServiceType")
                        .HasColumnType("int");

                    b.Property<int?>("HomeServiceType")
                        .HasColumnType("int");

                    b.Property<int?>("OtherServiceType")
                        .HasColumnType("int");

                    b.Property<int?>("PersonalServiceType")
                        .HasColumnType("int");

                    b.Property<int?>("ProfessionalServiceType")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceType")
                        .HasColumnType("int");

                    b.Property<int?>("TransportServiceType")
                        .HasColumnType("int");

                    b.HasKey("ListingId");

                    b.ToTable("ServicesDetails");
                });

            modelBuilder.Entity("Arzly.Api.Domain.ListingOwned.SportsDetails", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BallSportType")
                        .HasColumnType("int");

                    b.Property<int?>("BicyclePowerType")
                        .HasColumnType("int");

                    b.Property<int?>("BicycleType")
                        .HasColumnType("int");

                    b.Property<int?>("Condition")
                        .HasColumnType("int");

                    b.Property<int?>("GameRoomType")
                        .HasColumnType("int");

                    b.Property<int?>("GymType")
                        .HasColumnType("int");

                    b.Property<int?>("OutdoorType")
                        .HasColumnType("int");

                    b.Property<int?>("RacketSportType")
                        .HasColumnType("int");

                    b.Property<int?>("SupplementBrand")
                        .HasColumnType("int");

                    b.Property<int?>("SupplementType")
                        .HasColumnType("int");

                    b.Property<int?>("WaterSportType")
                        .HasColumnType("int");

                    b.Property<int?>("WinterSportType")
                        .HasColumnType("int");

                    b.HasKey("ListingId");

                    b.ToTable("SportsDetails");
                });

            modelBuilder.Entity("Arzly.Api.Domain.ListingOwned.VehiclesDetails", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AccessoryType")
                        .HasColumnType("int");

                    b.Property<int?>("BoatType")
                        .HasColumnType("int");

                    b.Property<int?>("CarBrand")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("CarFeatures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Condition")
                        .HasColumnType("int");

                    b.Property<int?>("FuelType")
                        .HasColumnType("int");

                    b.Property<int?>("Kilometers")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfDigits")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfDoors")
                        .HasColumnType("int");

                    b.Property<int?>("TransmissionType")
                        .HasColumnType("int");

                    b.Property<int?>("TruckBrand")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleColor")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleType")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("ListingId");

                    b.ToTable("VehiclesDetails");
                });

            modelBuilder.Entity("Arzly.Api.Infrastructure.Identity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AuthMethod")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BanExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("BanReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirebaseUid")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("PublicLocation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PublicName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "7c9e6679-7425-40de-944b-e07fc1f90ae7",
                            AccessFailedCount = 0,
                            AuthMethod = 0,
                            ConcurrencyStamp = "11c1fc1f-7505-4d93-95db-a21da536fd9d",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user1@arzly.com",
                            EmailConfirmed = false,
                            IsBanned = false,
                            IsDeleted = false,
                            IsVerified = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@ARZLY.COM",
                            NormalizedUserName = "USER1@ARZLY.COM",
                            PhoneNumberConfirmed = false,
                            PublicName = "User One",
                            SecurityStamp = "52d00af1-e161-4b17-9019-ebb2436c53ee",
                            TwoFactorEnabled = false,
                            UserName = "user1@arzly.com"
                        },
                        new
                        {
                            Id = "8f3b2a1c-5d4e-4f3a-9b8c-7d6e5f4a3b2c",
                            AccessFailedCount = 0,
                            AuthMethod = 1,
                            ConcurrencyStamp = "6f0fd301-275c-4ff0-af3f-66789c62b9ae",
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user2@arzly.com",
                            EmailConfirmed = false,
                            IsBanned = false,
                            IsDeleted = false,
                            IsVerified = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@ARZLY.COM",
                            NormalizedUserName = "USER2@ARZLY.COM",
                            PhoneNumberConfirmed = false,
                            PublicName = "User Two",
                            SecurityStamp = "cb374170-b83f-428d-9761-9bbedd536973",
                            TwoFactorEnabled = false,
                            UserName = "user2@arzly.com"
                        },
                        new
                        {
                            Id = "1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
                            AccessFailedCount = 0,
                            AuthMethod = 0,
                            ConcurrencyStamp = "b277b9c3-330e-496f-a352-885f50ff2d55",
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user3@arzly.com",
                            EmailConfirmed = false,
                            IsBanned = false,
                            IsDeleted = false,
                            IsVerified = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER3@ARZLY.COM",
                            NormalizedUserName = "USER3@ARZLY.COM",
                            PhoneNumberConfirmed = false,
                            PublicName = "User Three",
                            SecurityStamp = "776080c1-7250-4d86-9d7b-12a658b4736d",
                            TwoFactorEnabled = false,
                            UserName = "user3@arzly.com"
                        });
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.Chat", b =>
                {
                    b.HasOne("Arzly.Api.Infrastructure.Identity.AppUser", "Initiator")
                        .WithMany("ChatsInitiated")
                        .HasForeignKey("InitiatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arzly.Api.Domain.Entities.JobListing", "JobListing")
                        .WithMany("RelatedChats")
                        .HasForeignKey("JobListingId");

                    b.HasOne("Arzly.Api.Domain.Entities.Listing", "Listing")
                        .WithMany("RelatedChats")
                        .HasForeignKey("ListingId");

                    b.HasOne("Arzly.Api.Infrastructure.Identity.AppUser", "Receiver")
                        .WithMany("ChatsReceived")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Initiator");

                    b.Navigation("JobListing");

                    b.Navigation("Listing");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("Arzly.Api.Domain.Entities.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arzly.Api.Infrastructure.Identity.AppUser", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arzly.Api.Infrastructure.Identity.AppUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.JobListing", b =>
                {
                    b.HasOne("Arzly.Api.Domain.Entities.PickupLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arzly.Api.Infrastructure.Identity.AppUser", "Owner")
                        .WithMany("JobListings")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.Listing", b =>
                {
                    b.HasOne("Arzly.Api.Domain.Entities.Category", "Category")
                        .WithMany("Listings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arzly.Api.Infrastructure.Identity.AppUser", "Owner")
                        .WithMany("Listings")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arzly.Api.Domain.Entities.PickupLocation", "PickupLocation")
                        .WithMany("Listings")
                        .HasForeignKey("PickupLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arzly.Api.Domain.Entities.SubCategory", "SubCategory")
                        .WithMany("Listings")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Owner");

                    b.Navigation("PickupLocation");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.PickupLocation", b =>
                {
                    b.HasOne("Arzly.Api.Infrastructure.Identity.AppUser", "User")
                        .WithMany("DeliveryLocations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.SavedListing", b =>
                {
                    b.HasOne("Arzly.Api.Domain.Entities.Listing", "Listing")
                        .WithMany("SavedByUsers")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arzly.Api.Infrastructure.Identity.AppUser", "User")
                        .WithMany("SavedListings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.SearchQuery", b =>
                {
                    b.HasOne("Arzly.Api.Infrastructure.Identity.AppUser", "User")
                        .WithMany("SearchHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.SubCategory", b =>
                {
                    b.HasOne("Arzly.Api.Domain.Entities.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Arzly.Api.Infrastructure.Identity.AppUser", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Arzly.Api.Domain.Entities.Listing", "RelatedListing")
                        .WithMany()
                        .HasForeignKey("ListingId");

                    b.HasOne("Arzly.Api.Infrastructure.Identity.AppUser", "User")
                        .WithMany("CreatedTickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("RelatedListing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.TicketAttachment", b =>
                {
                    b.HasOne("Arzly.Api.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.TicketMessage", b =>
                {
                    b.HasOne("Arzly.Api.Infrastructure.Identity.AppUser", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arzly.Api.Infrastructure.Identity.AppUser", "Sender")
                        .WithMany("TicketMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arzly.Api.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.UserActivityLog", b =>
                {
                    b.HasOne("Arzly.Api.Infrastructure.Identity.AppUser", "Actor")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.UserPreference", b =>
                {
                    b.HasOne("Arzly.Api.Infrastructure.Identity.AppUser", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("Arzly.Api.Domain.Entities.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.UserReport", b =>
                {
                    b.HasOne("Arzly.Api.Domain.Entities.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId");

                    b.HasOne("Arzly.Api.Infrastructure.Identity.AppUser", "ReportedUser")
                        .WithMany("ReportsReceived")
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arzly.Api.Infrastructure.Identity.AppUser", "Reporter")
                        .WithMany("ReportsMade")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("ReportedUser");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("Arzly.Api.Domain.ListingOwned.BabyChildDetails", b =>
                {
                    b.HasOne("Arzly.Api.Domain.Entities.Listing", "Listing")
                        .WithOne("BabyChildDetails")
                        .HasForeignKey("Arzly.Api.Domain.ListingOwned.BabyChildDetails", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Arzly.Api.Domain.ListingOwned.ElectronicsDetails", b =>
                {
                    b.HasOne("Arzly.Api.Domain.Entities.Listing", "Listing")
                        .WithOne("ElectronicsDetails")
                        .HasForeignKey("Arzly.Api.Domain.ListingOwned.ElectronicsDetails", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Arzly.Api.Domain.ListingOwned.FashionDetails", b =>
                {
                    b.HasOne("Arzly.Api.Domain.Entities.Listing", "Listing")
                        .WithOne("FashionDetails")
                        .HasForeignKey("Arzly.Api.Domain.ListingOwned.FashionDetails", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Arzly.Api.Domain.ListingOwned.FurnitureDetails", b =>
                {
                    b.HasOne("Arzly.Api.Domain.Entities.Listing", "Listing")
                        .WithOne("FurnitureDetails")
                        .HasForeignKey("Arzly.Api.Domain.ListingOwned.FurnitureDetails", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Arzly.Api.Domain.ListingOwned.HobbiesDetails", b =>
                {
                    b.HasOne("Arzly.Api.Domain.Entities.Listing", "Listing")
                        .WithOne("HobbiesDetails")
                        .HasForeignKey("Arzly.Api.Domain.ListingOwned.HobbiesDetails", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Arzly.Api.Domain.ListingOwned.PetsDetails", b =>
                {
                    b.HasOne("Arzly.Api.Domain.Entities.Listing", "Listing")
                        .WithOne("PetsDetails")
                        .HasForeignKey("Arzly.Api.Domain.ListingOwned.PetsDetails", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Arzly.Api.Domain.ListingOwned.PhonesDetails", b =>
                {
                    b.HasOne("Arzly.Api.Domain.Entities.Listing", "Listing")
                        .WithOne("PhonesDetails")
                        .HasForeignKey("Arzly.Api.Domain.ListingOwned.PhonesDetails", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Arzly.Api.Domain.ListingOwned.RealEstateDetails", b =>
                {
                    b.HasOne("Arzly.Api.Domain.Entities.Listing", "Listing")
                        .WithOne("RealEstateDetails")
                        .HasForeignKey("Arzly.Api.Domain.ListingOwned.RealEstateDetails", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Arzly.Api.Domain.ListingOwned.ServicesDetails", b =>
                {
                    b.HasOne("Arzly.Api.Domain.Entities.Listing", "Listing")
                        .WithOne("ServicesDetails")
                        .HasForeignKey("Arzly.Api.Domain.ListingOwned.ServicesDetails", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Arzly.Api.Domain.ListingOwned.SportsDetails", b =>
                {
                    b.HasOne("Arzly.Api.Domain.Entities.Listing", "Listing")
                        .WithOne("SportsDetails")
                        .HasForeignKey("Arzly.Api.Domain.ListingOwned.SportsDetails", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Arzly.Api.Domain.ListingOwned.VehiclesDetails", b =>
                {
                    b.HasOne("Arzly.Api.Domain.Entities.Listing", "Listing")
                        .WithOne("VehiclesDetails")
                        .HasForeignKey("Arzly.Api.Domain.ListingOwned.VehiclesDetails", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.Category", b =>
                {
                    b.Navigation("Listings");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.JobListing", b =>
                {
                    b.Navigation("RelatedChats");
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.Listing", b =>
                {
                    b.Navigation("BabyChildDetails");

                    b.Navigation("ElectronicsDetails");

                    b.Navigation("FashionDetails");

                    b.Navigation("FurnitureDetails");

                    b.Navigation("HobbiesDetails");

                    b.Navigation("PetsDetails");

                    b.Navigation("PhonesDetails");

                    b.Navigation("RealEstateDetails");

                    b.Navigation("RelatedChats");

                    b.Navigation("SavedByUsers");

                    b.Navigation("ServicesDetails");

                    b.Navigation("SportsDetails");

                    b.Navigation("VehiclesDetails");
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.PickupLocation", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.SubCategory", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("Arzly.Api.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Arzly.Api.Infrastructure.Identity.AppUser", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("ChatsInitiated");

                    b.Navigation("ChatsReceived");

                    b.Navigation("CreatedTickets");

                    b.Navigation("DeliveryLocations");

                    b.Navigation("JobListings");

                    b.Navigation("Listings");

                    b.Navigation("Preferences");

                    b.Navigation("ReportsMade");

                    b.Navigation("ReportsReceived");

                    b.Navigation("SavedListings");

                    b.Navigation("SearchHistory");

                    b.Navigation("TicketMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
